### ISSUE TITLE
Functions as :key values

### ISSUE THREAD

**Issue by minad** [ahyatt/llm#110]
Hi!

Would it be possible to support functions as `:key` values? Functions are commonly used by the auth-source library in Emacs to slightly obfuscate secrets in the Emacs heap.

Right now I have to use funcall to unpack the secret:

~~~ elisp
(make-llm-openai-compatible
 :key (funcall (plist-get (car (auth-source-search :host "host" :user "apikey")) :secret))
 ...)
~~~

This would be better:

~~~ elisp
(make-llm-openai-compatible
 :key (plist-get (car (auth-source-search :host "host" :user "apikey")) :secret)
 ...)
~~~

**Comment by ahyatt** [comment]
This is a good idea, thanks for thinking of it and sending a PR!
