### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by roman** [ahyatt/llm#2]
Hello @ahyatt,

Thank you for contributing the code from this project. I'm looking forward to use it as it seems the one with the least amount of OpenAI coupling I've seen.

I'm interested in running this extension with an [ollama](https://ollama.ai/) backend. This tool is pretty neat as it allow clients to run various OSS data models in a straightforward way. The tool runs a local HTTP server that provides an [API](https://github.com/jmorganca/ollama/blob/main/docs/api.md) to query the various models. It also offers a CLI to interact with the various model installations, model tweaks, etc.

I've the impression that implementing a backend for this shouldn't be as challenging as you have lots of foundations going on already. I'm happy to help if there is some work that can be split out.

**Comment by roman** [comment]
This short [overview video](https://www.youtube.com/watch?v=swNeoKGFkQM) is also very informative.

**Comment by ahyatt** [comment]
Thanks, I hadn't heard of ollama.  Is the code to interface with ollama something you are interesting in contributing?  And, if so, do you have FSF papers?  Otherwise, it seems like something I can work on, but I also have several other next steps and don't know yet how I'll prioritize things.

**Comment by roman** [comment]
Hey @ahyatt,

I can run the `llm-test.el` file using `ert` no problem. However, I'm unsure how to run `llm-tester` for the various backends (OpenAI, Vertex, etc). 

Are there some steps you follow to test that?

**Comment by ahyatt** [comment]
Yes, for that I create a provider, and run `llm-tester-all` on it, and look in the Messages buffer for the output.

For the FSF paperwork, if you wanted to pursue contributing, you need to fill [this](http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob_plain;f=doc/Copyright/request-assign.future;hb=HEAD) out and follow the instructions.  Let me know soon if you intend to do that, otherwise, I took a look at the ollama API and it should be fairly trivial for me to do this.

**Comment by roman** [comment]
> For the FSF paperwork, if you wanted to pursue contributing, you need to fill [this](http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob_plain;f=doc/Copyright/request-assign.future;hb=HEAD) out and follow the instructions. Let me know soon if you intend to do that

I filled the form and submit it a couple of minutes ago

> I took a look at the ollama API and it should be fairly trivial for me to do this.

If you feel empowered to do this work, please don't wait for me. I'm more than happy to review it 👍

**Comment by ahyatt** [comment]
I've added an ollama provider today, @roman can you try it out and make sure it works for you?  Also, please check the embeddings and make sure they make sense - are similar concepts closer in embedding space?

**Comment by roman** [comment]
> I've added an ollama provider today, @roman can you try it out and make sure it works for you?

It is working 👍 , thanks!

> Also, please check the embeddings and make sure they make sense - are similar concepts closer in embedding space?

To be quite honest with you, I'm new to the LLM game, and I'm not acquainted yet with the concept of embeddings or how to use them, let me get some knowledge about that and get back to you

One Nit, what do you think about allowing ollama to be served from another host that is not localhost? I can see a setup where a company runs an ollama instance for various employees and you can use that instead.

**Comment by ahyatt** [comment]
About non-localhost serving: sure, I can do that, but is it possible?  IIRC, localhost serving often will forbid outside connections.  So I guess it depends on if ollama is designed to be used that way.

**Comment by roman** [comment]
> but is it possible? IIRC, localhost serving often will forbid outside connections. So I guess it depends on if ollama is designed to be used that way.

I think you can setup ollama to bind on `0.0.0.0` to allow remote connections. I can imagine a more sophisticated setup (https, authentication, etc.) being built on top of that.

**Comment by roman** [comment]
By the way, is there any project that sits on top of this project to integrate with org babel blocks, or have a chat buffer?

I have the impression the goal of this project is to be nimble and serve as a lower tier for more sophisticated integrations with the editor.

**Comment by ahyatt** [comment]
One of my other projects, `ekg` uses this, but it's for a pretty specialized use.  There are a number of other emacs Chat GPT integrations and I've started contacting them to use this library.  Hopefully they will switch soon - it would make sense for them, since they already are getting requests to use different backends, and it isn't great for them to have to each figure out how to make the calls and handle streaming.

**Comment by roman** [comment]
Sounds good,

I'm going to close this ticket as completed now.

Thanks for the quick turnaround about this @ahyatt your work and efforts are highly appreciated
