### ISSUE TITLE
Support function calling with ollama

### ISSUE THREAD

**Issue by s-kostyaev** [ahyatt/llm#51]
https://github.com/ollama/ollama/pull/5284 merged. In new ollama release function calling will be improved. I'd like to use it with `llm` library.

**Comment by ahyatt** [comment]
this is great to see - I'll work on it for the next version (maybe this weekend or next).

**Comment by ahyatt** [comment]
I've merged this into `main` and will create a release soon.  One question before I do is that, in this new release, I provide the `llm-capabilities` for ollama to change based on version.  I based it off the ollama [list of models that support tools](https://ollama.com/search?c=tools).  However, the similar [list of models that support embeddings](https://ollama.com/search?q=&c=embedding), is much smaller than I would have thought.  I probably should change that as well, if it's accurate.  But is it?

**Comment by s-kostyaev** [comment]
Looks accurate. But take into account that this lists are dynamic.
