### ISSUE TITLE
Error in function calling with ollama

### ISSUE THREAD

**Issue by ultronozm** [ahyatt/llm#70]
Evaluating

```elisp
(let ((provider (make-llm-ollama :chat-model "mistral:latest")))
  (llm-tester-function-calling-conversation-sync provider))
```

yields

```
LLM request failed with code 400: Bad Request (additional information: ((error . json: cannot unmarshal array into Go struct field ChatRequest.messages of type string)))
```

I get the same error with "llama3.1-latest".

**Comment by ahyatt** [comment]
Good bug, thanks for this.  Ollama doesn't really have any documentation on function conversations as far as I can tell.  I explored some examples and saw some differences to what I was doing, but even fixes those differences, I wasn't able to get it to work, yet.  Let me know the priority on your side, but it's going to be difficult to fix this one.
