### ISSUE TITLE
Do not enforce order of messages

### ISSUE THREAD

**Issue by meain** [ahyatt/llm#86]
Wondering if we could add in a option to pass in a plist(or something else) for `text` in [`llm-make-chat-prompt`
](https://github.com/ahyatt/llm/blob/805ce30fc8fb0c7e0cbbc90eca61a2ac81d0c061/llm.el#L228-L231) so that I can have non alternating messages. From what I can tell, you don't have to have the messages in an alternating format(ie user-assistant-user...). I have tested this with OpenAI, Anthropic and Ollama(llama3.2). I'm pretty sure I've used similar prompts with phi and gemma models as well.

I can [manually create messages like this](https://github.com/meain/yap/blob/c6503a0e96a5fac6561fe0ac71432d1c2780a820/yap-utils.el#L93-L103), but wondering if this could benefit from being supported within the package.

You can try running the following below and you'll get something like `You said "Hello!" and then "Goodbye!"`.

```bash
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4o-mini",
    "messages": [
      { "role": "system","content": "You are a helpful assistant." },
      { "role": "user","content": "Hello!" },
      { "role": "user","content": "Goodbye!" },
      { "role": "user","content": "What all did I say above?" }
    ]
  }'
```

**Comment by ahyatt** [comment]
You can get this effect by manually constructing the `llm-chat-prompt` struct - the `llm-make-chat-prompt` is a helper method.  However, it isn't the case that all systems allow this.  In particular, Gemini does not allow it, so I'd be careful baking consecutive role messages like this into anything that could take any model.

**Comment by meain** [comment]
> However, it isn't the case that all systems allow this. In particular, Gemini does not allow it ...

Ahh, I see, I was not aware of that. Makes sense.
