### ISSUE TITLE
Add ability to change open api base url

### ISSUE THREAD

**Issue by s-kostyaev** [ahyatt/llm#9]
Hi.
There are many open source solutions mimicking to open ai api. It will be useful if we can use it with llm library. For now there is no working local embedding solution working with llm. Ollama's and llama.cpp are broken now (fix in progress). I wrote simple one myself, but I can't use it with llm. I can also mimic open ai api and use your library. Since there is already supported vss extension for sqlite in 29.2, it will be very useful.

**Comment by ahyatt** [comment]
Thanks for opening this.  I'm not sure it's a good idea to have an option like that yet for general use; I'd like to be able to explain a more normal use-case that needs it first.  I'd like to un-block you, though, so I could perhaps create a branch for this, and when if there's a general need for it, I can merge it into the main branch.  Would that be OK?

**Comment by s-kostyaev** [comment]
No need it to unblock me, I wrote elisp to get embeddings from my local api and can wait it to be fixed in llama.cpp and ollama upstream. It can be useful with something like https://github.com/oobabooga/text-generation-webui or https://github.com/BerriAI/litellm

**Comment by r0man** [comment]
I'm also interested in this, since I need to go through a proxy that uses mutual TLS (I also need to specify a client certificate and CLI eventually, but that's another storry) to talk to the OpenAI API.

**Comment by ahyatt** [comment]
@r0man I recently received another similar request via another channel - do you need an API key for your use?  The other request for proxy functionality was basically to use a proxy but the proxy takes care of authentication.

**Comment by ahyatt** [comment]
OK, all, I've pushed a fix for this, which is a new provider, `llm-openai-compatible` (see the README for more details).  Please let me know if that works.

**Comment by r0man** [comment]
Thank you @ahyatt. I'm not able to test this at the moment, since I still have an issue with the client certificate I need to use. But it looks good to me.
