### ISSUE TITLE
Fail to connect to Azure OpenAI Endpoint

### ISSUE THREAD

**Issue by tsoernes** [ahyatt/llm#91]
`llm                            0.17.4         `

I have tried this:
```elisp
(defun gptel-api-key ()
  (interactive)
  (or (getenv "OAI_GPT4O_06082024_API_KEY")
      (error "API key not found in environment variables")))

(make-llm-openai-compatible
                                 :url "https://XXXX.openai.azure.com/openai/deployments/m-gpt-4o-mini-18072024"
                                 :key (gptel-api-key)
                                 :chat-model "m-gpt-4o-mini-18072024")
```
But it fails to connect.

I have a configuration for `gptel` that works. It looks like this:
```elisp
(setq gptel-backend (gptel-make-azure "Azure-1-GPT-4o-mini"
                      :protocol "https"
                      :host "XXXX.openai.azure.com"
                      :endpoint "/openai/deployments/m-gpt-4o-mini-18072024/chat/completions?api-version=2024-08-01-preview"
                      :stream t
                      :key #'gptel-api-key
                      :models '(m-gpt-4o-mini-18072024)))

```

I suppose this is related to #36 but I don't know how to configure.

**Comment by ahyatt** [comment]
I'll take a look at this - I've never used Azure, but it should in theory work.  I assume you're getting some sort of error from the Azure server, can you let me know what it is?

**Comment by tsoernes** [comment]
I use it in conjunction with magit-gptcommit like this:

```elisp
(use-package! magit-gptcommit
  :demand t
  :after magit
  :bind (:map git-commit-mode-map
              ("C-c C-g" . magit-gptcommit-commit-accept))
  :init
  ;; (require 'llm-openai-compatible)
  (require 'llm-openai)
  :custom
  (magit-gptcommit-llm-provider (make-llm-openai-compatible
                                 :url "https://XXXX.openai.azure.com/openai/deployments/m-gpt-4o-mini-18072024"
                                 :key (gptel-api-key)
                                 :chat-model "m-gpt-4o-mini-18072024"))

  :config
  ;; Enable magit-gptcommit-mode to watch staged changes and generate commit message automatically in magit status buffer
  ;; This mode is optional, you can also use `magit-gptcommit-generate' to generate commit message manually
  ;; `magit-gptcommit-generate' should only execute on magit status buffer currently
  ;; (magit-gptcommit-mode 1)

  ;; Do not output warning when using llm
  (setq llm-warn-on-nonfree nil)

  ;; Add gptcommit transient commands to `magit-commit'
  ;; Eval (transient-remove-suffix 'magit-commit '(1 -1)) to remove gptcommit transient commands
  (magit-gptcommit-status-buffer-setup))
```

When running `magit-gpt-commit-generate` it says: "GPT commit: Response Error: Open AI returned error: nil message: Resource not found". Nothing is outputted to any error or message buffer.

(Note that I use the same resource and URL with gptel, which works).

**Comment by ahyatt** [comment]
Thanks, I think the format of the URL that Azure is using is a bit weird that necessitates a very slighty more involved solution than just using `llm-openai-compatible` as a provider.  I've created a new branch `azure` that has a new `llm-azure.el` that at least gets me past the issue you reported.  However, my authentication is also not working.  I'm not sure if that needs another customization, or I'm just not doing it right.  It's my first time working with Azure. 

If you could try it out with the new branch, that would help - but I can work more on this in the next few days.

**Comment by tsoernes** [comment]
I checked out the branch and now use

```elisp
  (require 'llm-azure)
  :custom
  (magit-gptcommit-llm-provider (make-llm-azure
                                 :url "https://XXX.openai.azure.com/openai/deployments/m-gpt-4o-mini-18072024"
                                 :key (gptel-api-key)
                                 :chat-model "m-gpt-4o-mini-18072024"))
```

But get the very same error.

**Comment by ahyatt** [comment]
The README has instructions on how to set this up, your url should only be "https://XXX.openai.azure.com/".

**Comment by tsoernes** [comment]
I have tried that also;

``elisp
  (magit-gptcommit-llm-provider (make-llm-azure
                                 ;; :url "https://XX.openai.azure.com/openai/deployments/m-gpt-4o-mini-18072024"
                                 :url "https://XXX.openai.azure.com/"
                                 :key (gptel-api-key)
                                 :chat-model "m-gpt-4o-mini-18072024"))
```
But get an error in magit-gptcommit "GPT commit: Response Error: Unknown error".

**Comment by tsoernes** [comment]
It works! Thank you

**Comment by ahyatt** [comment]
Thanks, I'll merge this in!
