### ISSUE TITLE
[FR] Add ability to calculate multiple embeddings in single call

### ISSUE THREAD

**Issue by s-kostyaev** [ahyatt/llm#92]
Hi! It would be great if we will have ability to calculate multiple embeddings in single api call. For example in ollama you can do it like this https://github.com/ollama/ollama/blob/main/docs/api.md#request-multiple-input
Can we extend api to make it possible? I think it can improve `elisa` speed significantly.

**Comment by ahyatt** [comment]
Yeah, that seems like a good idea to add, thanks.  I'd like to use it as well in my ekg project.  I'll work on this soon.

**Comment by ahyatt** [comment]
It *should* work.  If you are getting this error, it makes me think you may need to re-load `llm-provider-utils` (and probably `llm-ollama` too).  `llm-provider-utils` defines `llm-batch-embeddings` in a base struct provider that should cover ollama.

**Comment by s-kostyaev** [comment]
It works fine after reloading emacs. Thank you!
Are there any follback implementation for providers that doesn't support batch embeddings? Or should I support it on my side?

**Comment by ahyatt** [comment]
There isn't a fallback - I think, like most of LLM functionality, you should detect it via the `llm-capabilities` and if it isn't supported, decide what you want to do: either fall back to non-batch embeddings yourself, or, if you think the performance would be notaby degraded, tell the user to switch models.

**Comment by ahyatt** [comment]
I'm going to close off this FR now, since it is in the latest release.  Thanks again for suggesting it!
